services:
  mongodb:
    container_name: songy-mongodb
    # mongo:4.4.18 does not need AVX instructions, so it instead if
    # your devices does not support it
    image: mongo:latest
    restart: unless-stopped
    ports:
      - ${MONGODB_DATABASE_PORT}:27017
    volumes:
      - ./mongodb/db:/data/db
      - ./mongodb/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_DATABASE_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_DATABASE_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGODB_DATABASE_NAME}

  api:
    tty: true
    build:
      context: ./api/
    restart: unless-stopped
    container_name: songy-api
    volumes:
      - ./api/src:/usr/src/app/src
      - ./.env:/usr/src/.env
      - ./shared:/usr/src/shared
    ports:
      - ${API_PORT}:${API_PORT}
  web:
    tty: true
    build:
      context: ./web/
    restart: unless-stopped
    container_name: songy-web
    ports:
      - 80:80
